### ISSUE TITLE
Rename run_scrc_server and ~/.scrc

### ISSUE THREAD

**Issue by agbeltran** [FAIRDataPipeline/data-registry#73] opened 2021-06-24 12:53 UTC
I would like to suggest to rename the script:
https://github.com/ScottishCovidResponse/data-registry/blob/master/scripts/run_scrc_server
to ```start_scrc_server``` (to complement the ```stop_scrc_server``` option) and also match with the usual start/stop options.

Should we also rethink the inclusion of ```scrc``` in the name?

**Comment by richardreeve** [comment] 2021-06-24 16:41
Good idea. I should also say that @kzscisoft will also be creating two simple `fair` commands - `fair start` and `fair stop` that will start and stop the registry server, so we don't need to know what the correct script is. We could even add `fair install` to the list too if we wanted to do the actual installation... ?

**Comment by richardreeve** [comment] 2021-06-24 17:30
@alahiff @nathan-cummings-ukaea - I think we want to do a bit more renaming before the 1.0 release, so maybe it's worth putting them in here...

At the moment we store everything in `~/.scrc`, but it should surely be `~/.fair` for consistency. We're also going to be putting quite a bit more stuff in there (a default data store, for instance), so can we move everything(?) in `~/.scrc` to `~/.fair/registry`? Is there anything that should stay at the top level?

**Comment by kzscisoft** [comment] 2021-06-25 07:06
> Good idea. I should also say that @kzscisoft will also be creating two simple `fair` commands - `fair start` and `fair stop` that will start and stop the registry server, so we don't need to know what the correct script is. We could even add `fair install` to the list too if we wanted to do the actual installation... ?
> 
Yes I can confirm this will be the case, the commands `fair server start` and `fair server stop` will be available.

An extra is if the user only wants to synchronise/push-pull (not open the browser etc) then it will start the server for the duration of the command, and keep it running until there are no ongoing processes (I know @richardreeve mentioned the possibility of multiple instances etc. so this will cover that) and then automatically stop it again.

**Comment by kzscisoft** [comment] 2021-06-25 07:11
> @alahiff @nathan-cummings-ukaea - I think we want to do a bit more renaming before the 1.0 release, so maybe it's worth putting them in here...
> 
> At the moment we store everything in `~/.scrc`, but it should surely be `~/.fair` for consistency. We're also going to be putting quite a bit more stuff in there (a default data store, for instance), so can we move everything(?) in `~/.scrc` to `~/.fair/registry`? Is there anything that should stay at the top level?

To add, in the case of the CLI the folder will be `~/.fair/cli/` 🙂

**Comment by alahiff** [comment] 2021-06-25 08:11
> I know @richardreeve mentioned the possibility of multiple instances etc. so this will cover that

Is there a use case for multiple local registries on the same machine? If this is the case maybe we should use `~/.fair/registry/<label>` rather than just `~/.fair/registry` so that it's possible to have multiple distinct named registries.

**Comment by nathan-cummings-ukaea** [comment] 2021-06-25 08:23
> > I know @richardreeve mentioned the possibility of multiple instances etc. so this will cover that
> 
> Is there a use case for multiple local registries on the same machine? If this is the case maybe we should use `~/.fair/registry/<label>` rather than just `~/.fair/registry` so that it's possible to have multiple distinct named registries.

Are we talking multiple local registries, or multiple sessions uploading to a single local repo simultaneously?

**Comment by kzscisoft** [comment] 2021-06-25 09:45
Sorry @alahiff I think I caused confusion! I meant multiple sessions with the CLI so for example multiple code runs/syncs

**Comment by richardreeve** [comment] 2021-06-25 10:20
> Is there a use case for multiple local registries on the same machine? If this is the case maybe we should use `~/.fair/registry/<label>` rather than just `~/.fair/registry` so that it's possible to have multiple distinct named registries.

I can't think of a reason to support this - supporting one user and multiple registries would make it possible to have merge conflicts on your personal namespace when we push to a remote, which is one of the things we are explicitly trying to avoid.

**Comment by alahiff** [comment] 2021-06-25 10:33
The change from `~/.scrc` to `~/.fair/registry` has been implemented in https://github.com/ScottishCovidResponse/data-registry/commit/a92fa4a2a25c13329319a920d2479a8d159a7744

Anyone running this:
```
/bin/bash -c "$(curl -fsSL https://data.scrc.uk/static/localregistry.sh)"
```
will end up with a local registry in the new location. The command names have not been updated yet.

**Comment by richardreeve** [comment] 2021-06-25 10:36
I know I'm being picky, but I might do a global search and replace of `SCRC_HOME` (and other variables?) with `FAIR_HOME` just for consistency...

**Comment by alahiff** [comment] 2021-06-25 11:19
Many more things renamed in https://github.com/ScottishCovidResponse/data-registry/commit/9a3af8b99d076979f904c48b6c31f15e867a7f6b https://github.com/ScottishCovidResponse/data-registry/commit/47ca4b1465593a818d48871291b89422a8ef4df1 https://github.com/ScottishCovidResponse/data-registry/commit/f384860564034810ebcc8d5923670405f6378efa. Now it's just documentation (main README and docs/) and the names of those scripts themselves.

**Comment by richardreeve** [comment] 2021-06-25 14:11
So we need names for the start and stop scripts... how about `start_fair_registry` and `stop_fair_registry`? Or ending in `_server` (as currently)?

**Comment by agbeltran** [comment] 2021-06-25 16:23
did @kzscisoft said that we will have the commands ```fair server start``` etc (or ```fair registry start``` might be better) - https://github.com/ScottishCovidResponse/data-registry/issues/73#issuecomment-868275285

I tested the new installation procedure by running
`
/bin/bash -c "$(curl -fsSL https://data.scrc.uk/static/localregistry.sh)"
`
and then 
`
~/.fair/registry/scripts/run_scrc_server
`
but I am getting an error when loading localhost:
``` A server error occurred.  Please contact the administrator.```

**Comment by alahiff** [comment] 2021-06-25 16:54
@agbeltran I tried the exact commands you've written and it works for me (unfortunately!).

**Comment by kzscisoft** [comment] 2021-06-28 07:02
@agbeltran Both @soniamitchell and I had this issue and found it worked by reinstalling and restarting our machines.

**Comment by nathan-cummings-ukaea** [comment] 2021-06-28 07:16
It may not be the reason, but I also had this problem due to the fact that I had not stopped the server before removing .scrc/

The process was still running, hogging the port, despite the directory being gone. I manually killed the process and started then ran the new registry and all was well.

I suspect restarting your machine would have the same effect so that could be what was going on.

**Comment by alahiff** [comment] 2021-06-28 07:39
It might be useful to update the server start script to check for any existing local registries running from the same directory and kill it (or give a warning). All the required information can be obtained from `ps`, e.g.
```
/home/andrewlahiff/.fair/registry/venv/bin/python /home/andrewlahiff/.fair/registry/manage.py runserver
```

**Comment by richardreeve** [comment] 2021-06-28 11:33
> did @kzscisoft said that we will have the commands `fair server start` etc (or `fair registry start` might be better) - [#73 (comment)](https://github.com/FAIRDataPipeline/data-registry/issues/73#issuecomment-868275285)

Yes, you're right - @kzscisoft said he'd implement that, though his code will presumably just call the start and stop scripts that get installed with the registry! Shall we call the `fair` commands `fair registry [start|stop]` and the script `start_fair_registry` and `stop_fair_registry` then? I think it makes it clearer what they are, though obviously they are also servers...

**Comment by richardreeve** [comment] 2021-06-28 11:34
Should be a relatively painless fix except if any of the data pipeline APIs (@soniamitchell, @mjb3?) start and stop the registry themselves?

**Comment by alahiff** [comment] 2021-06-29 07:54
This has been done, closing.

**Closed by alahiff** 2021-06-29 07:54 UTC

**Comment by mjb3** [comment] 2021-06-29 08:31
> Should be a relatively painless fix except if any of the data pipeline APIs (@soniamitchell, @mjb3?) start and stop the registry themselves?

Apologies,  I missed this yesterday - no mine doesn't, am just assuming for the time being that the user handles starting and stopping the local DR. Cheers
